name = "sharedpearls"
main = "src/index.ts"
type = "javascript"
compatibility_date = "2024-01-01"

[build]
command = ""

[env.production]
name = "sharedpearls"
route = "www.sharedpearls.com/*"
zone_id = ""
